services:
  - type: web
    name: reconciler-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://davidwilliams1602:Carolinejean1983@clusterrecon.92y8e.mongodb.net/invoice_reconciliation?retryWrites=true&w=majority&appName=Clusterrecon
      - key: JWT_SECRET
        value: your-secure-jwt-secret-here
      - key: CORS_ORIGIN
        value: https://reconciler-frontend.onrender.com
      - key: GOOGLE_VISION_API_KEY
        sync: false
      - key: XERO_CLIENT_ID
        sync: false
      - key: XERO_CLIENT_SECRET
        sync: false
      - key: XERO_TENANT_ID
        sync: false
      - key: DEXT_API_KEY
        sync: false
      - key: DEXT_CLIENT_ID
        sync: false
      - key: DEXT_CLIENT_SECRET
        sync: false

  - type: static
    name: reconciler-frontend
    rootDir: frontend-new
    nodeVersion: 18.17.1
    buildCommand: ./build.sh
    publishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: REACT_APP_API_URL
        value: https://reconciler-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: no-cache