version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Database
      - DATABASE_URL=postgresql://postgres:password@db:5432/invoice_reconciler
      
      # Security
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      
      # Email processing
      - EMAIL_POLLING_ENABLED=${EMAIL_POLLING_ENABLED:-false}
      - EMAIL_POLLING_INTERVAL_MINUTES=${EMAIL_POLLING_INTERVAL_MINUTES:-60}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SERVER=${EMAIL_SERVER:-imap.gmail.com}
      - EMAIL_FOLDER=${EMAIL_FOLDER:-INBOX}
      
      # Google Vision integration
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
      
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=invoice_reconciler
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: 